version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
