services:
  flask-app:
    container_name: project2 
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_DBNAME=lfg_app
      - MONGO_URI=mongodb://admin:secret@mongodb:27017
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
    depends_on:
      - mongodb

  mongodb:
    container_name: project2-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
