services:
  flask-app:
    container_name: project22
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_DBNAME=lfg_app
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/lfg_app?authSource=admin
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_PORT=5000
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    container_name: project2-mongodbA
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--username=admin", "--password=secret", "--authenticationDatabase=admin", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  mongodb-data:
    driver: local